name: 🚀 App Feature Request
description: Request a feature/enhancement
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## App Feature Request Description"
  - type: markdown
    attributes:
      value: "Please first search in both issues & discussions for your enhancement and make sure your app is up to date."
  - type: textarea
    id: describe
    attributes:
      label: Describe the Feature/Enhancement
      description: Please help us understand what you want.
      placeholder: What is your vision?
    validations:
      required: true
  - type: textarea
    id: the-why
    attributes:
      label: Why would this be helpful?
      description: Please help us understand why this would enhance your experience.
      placeholder: Explain the "why" or "use case".
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Future Implementation (Screenshot)
      description: Please help us visualize by including a doodle or screenshot.
      placeholder: How could this look or where could it go?
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## App Current Implementation"
  - type: dropdown
    id: version
    attributes:
      label: Audiobookshelf App Version
      description: Please ensure your app is up to date. *If you are using a 3rd-party app, please reach out to them directly.*
      multiple: true
      options:
        - Android App - 0.9.74
        - iOS App - 0.9.74
        - Android App - 0.9.73
        - iOS App - 0.9.73
    validations:
      required: true
  - type: textarea
    id: current-image
    attributes:
      label: Current Implementation (Screenshot)
      description: What screen were you looking at when you thought of this enhancement?
      placeholder: If an image is not applicable, please explain why.
